//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMoviesJuly2018.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Movie
    {
        public int Id { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 2)]
        public string Title { get; set; }

        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:dd-MMM-yyyy}", ApplyFormatInEditMode =true)]
        public Nullable<System.DateTime> ReleaseDate { get; set; }

        [Required] // think about what you have or haven't made Null or nullable in the database
        [StringLength(30)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z' '-'\s\-]*$", ErrorMessage ="Genre must begin with a capital letter.")]

        public string Genre { get; set; }

        [Range(0, 1000)]
        [DataType(DataType.Currency)]
        public Nullable<decimal> Price { get; set; }

        public string ImageURL { get; set; }
    }
}
